color=input("Enter any color: ")
name=input("enter a name: ")
object=input("enter an object: git")
print("Roses are "+ color+",")
print("sky is blue,")
print("My name is "+name+".")
print("And you are "+object)